### ISSUE TITLE
Ability to apply a compilation_level of "none"

### ISSUE THREAD

**Issue by doodlemoonch** [oyvinmar/grails-closure-compiler#7] opened 2013-04-08 15:54 UTC
It'd be useful to be able to turn off compilation in development environments for debugging JavaScript in dev/test

**Comment by dooburt** [comment] 2013-04-08 15:56
I second this.

**Comment by ghost** [comment] 2013-06-27 16:57
this is a duplicate of #4

**Closed as completed** 2013-08-03 10:20 UTC
Labels: duplicate
